export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      {/* Navigation */}
      <nav className="border-b border-slate-700/50 bg-slate-900/50 backdrop-blur-sm">
        <div className="container mx-auto flex items-center justify-between px-6 py-4">
          <a href="/" className="flex items-center gap-3">
            <img src="/icon.svg" alt="Kitha" className="h-8 w-8" />
            <span className="text-xl font-extrabold">
              <span className="text-white">kith</span>
              <span className="text-[#F97316]">a</span>
            </span>
          </a>
          <a
            href="/"
            className="rounded-lg bg-slate-700/50 px-4 py-2 text-sm text-slate-300 transition hover:bg-slate-700"
          >
            Back to Home
          </a>
        </div>
      </nav>

      <main className="container mx-auto px-6 py-12">
        <div className="mx-auto max-w-3xl">
          <h1 className="mb-8 text-4xl font-bold text-white">Terms of Service</h1>
          <p className="mb-8 text-slate-400">Last updated: January 2025</p>

          <div className="space-y-8 text-slate-300">
            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">1. Acceptance of Terms</h2>
              <p>
                By accessing or using Kitha (&quot;the Service&quot;), including our Chrome extension and web application, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">2. Description of Service</h2>
              <p>
                Kitha is an AI detection tool that analyzes tweets on X (Twitter) to estimate the probability that they were generated by artificial intelligence. The Service consists of:
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6">
                <li>A Chrome browser extension that displays AI probability badges on tweets</li>
                <li>A web dashboard for managing your account and viewing usage statistics</li>
                <li>Backend AI inference services for analyzing tweet content</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">3. Account Registration</h2>
              <p>To use Kitha, you must:</p>
              <ul className="mt-4 list-disc space-y-2 pl-6">
                <li>Provide a valid email address</li>
                <li>Be at least 13 years of age</li>
                <li>Keep your API key confidential and secure</li>
                <li>Not share your account with others</li>
              </ul>
              <p className="mt-4">
                You are responsible for all activity that occurs under your account.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">4. Free and Pro Plans</h2>
              <div className="space-y-4">
                <div>
                  <h3 className="mb-2 text-lg font-medium text-white">Free Plan</h3>
                  <ul className="list-disc space-y-1 pl-6">
                    <li>Limited to 50 tweet scans per day</li>
                    <li>Daily limit resets at midnight UTC</li>
                    <li>Access to basic AI detection features</li>
                  </ul>
                </div>
                <div>
                  <h3 className="mb-2 text-lg font-medium text-white">Pro Plan ($5/month)</h3>
                  <ul className="list-disc space-y-1 pl-6">
                    <li>Unlimited tweet scans</li>
                    <li>Priority support</li>
                    <li>Early access to new features</li>
                  </ul>
                </div>
              </div>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">5. Payment and Billing</h2>
              <ul className="list-disc space-y-2 pl-6">
                <li>Pro subscriptions are billed monthly through Stripe</li>
                <li>You may cancel your subscription at any time through the billing portal</li>
                <li>Cancellation takes effect at the end of your current billing period</li>
                <li>No refunds are provided for partial months</li>
                <li>Promotional discounts (e.g., first month free) apply to the first billing cycle only</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">6. Acceptable Use</h2>
              <p>You agree NOT to:</p>
              <ul className="mt-4 list-disc space-y-2 pl-6">
                <li>Use the Service for any illegal purpose</li>
                <li>Attempt to reverse engineer, decompile, or extract our AI models</li>
                <li>Circumvent rate limits or usage restrictions</li>
                <li>Share your API key or allow others to use your account</li>
                <li>Use automated scripts to abuse the Service</li>
                <li>Harass, defame, or discriminate against others based on AI detection results</li>
                <li>Resell or redistribute the Service without permission</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">7. Accuracy Disclaimer</h2>
              <p>
                <strong className="text-white">AI detection is not 100% accurate.</strong> Kitha provides probability estimates based on machine learning models. Results should be interpreted as indicators, not definitive proof.
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6">
                <li>False positives may occur (human content flagged as AI)</li>
                <li>False negatives may occur (AI content not detected)</li>
                <li>Detection accuracy may vary based on writing style, language, and content type</li>
                <li>Do not use Kitha results as the sole basis for consequential decisions</li>
              </ul>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">8. Intellectual Property</h2>
              <p>
                The Service, including our AI models, software, design, and branding, is owned by Kitha and protected by intellectual property laws. You may not copy, modify, or distribute any part of the Service without explicit permission.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">9. Limitation of Liability</h2>
              <p>
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, KITHA SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SERVICE. THIS INCLUDES DAMAGES FOR:
              </p>
              <ul className="mt-4 list-disc space-y-2 pl-6">
                <li>Inaccurate AI detection results</li>
                <li>Service interruptions or downtime</li>
                <li>Loss of data or unauthorized access</li>
                <li>Actions taken based on detection results</li>
              </ul>
              <p className="mt-4">
                Our total liability shall not exceed the amount you paid for the Service in the past 12 months.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">10. Termination</h2>
              <p>
                We reserve the right to suspend or terminate your account at any time for violation of these Terms. You may also delete your account at any time by contacting us.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">11. Changes to Terms</h2>
              <p>
                We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms. We will notify users of significant changes via email or in-app notification.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">12. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with applicable laws. Any disputes arising from these Terms or your use of the Service shall be resolved through good-faith negotiation.
              </p>
            </section>

            <section>
              <h2 className="mb-4 text-2xl font-semibold text-white">13. Contact</h2>
              <p>
                For questions about these Terms of Service, please contact us via DM on X (Twitter) at{' '}
                <a href="https://x.com/OrdinaryWeb3Dev" target="_blank" rel="noopener noreferrer" className="text-purple-400 hover:text-purple-300">
                  @OrdinaryWeb3Dev
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-800 py-8">
        <div className="container mx-auto px-6 text-center text-sm text-slate-500">
          <p>&copy; 2025 Kitha. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}
